version: 2

models:
  - name: stg_customers
    description: "Dados de clientes, tratados e padronizados"
    columns:
      - name: customer_id
        description: "ID único do cliente"
        tests:
          - not_null
          - unique
      - name: email
        description: "Email do cliente"
        tests:
          - not_null

  - name: stg_orders
    description: "Pedidos realizados por clientes"
    columns:
      - name: order_id
        description: "ID do pedido"
        tests:
          - not_null
          - unique
      - name: status
        description: "Status do pedido"
        tests:
          - accepted_values:
              values: ['completo', 'cancelado']

  - name: stg_products
    description: "Produtos do catálogo"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: category
        description: "Categoria do produto"
        tests:
          - not_null

  - name: stg_order_items
    description: "Itens de pedidos, com produtos e quantidades"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null

  - name: stg_cancelamentos
    description: "Pedidos cancelados com motivo e data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
